### PR TITLE
React  Todo App

### PR DESCRIPTION
**Pull request by Ntwali-Josue**
### In this Pull request , I: 

- [x] Create a react todo web page.
- [x] Add functionalities of `add`, `edit`, `delete` a task.
- [x] Use `React Routers` to other more than one page.
- [x] Add a nested `About` page, using `useRouteMatch()` hook.
- [x] Deploy the app with `gh-pages`.

### CODE REVIEW

**Review by Fondem-Jr — CHANGES_REQUESTED** [review]
### Hi @Ntwali-Josue  🙋‍♀️, 

Good job so far! 👌
There are some issues that you still need to work on but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


#  Required Changes ♻️ 🚧
_Check the comments under the review._

I can see you have refactored your project is well done using class components.

- [ ] Kindly do the same for `Functional components` 🙂 
- [ ] Kindly give a descriptive pull request 🙂 

###  Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ntwali-Josue** [comment]
Hey, @Fondem-Jr thanks a lot for reviewing my pull request, especially for pointing on the pull description that I forgot to work on. 
However, regarding the review you gave me about using `Functional components`, I would like to say that, since in the project requirements, we had it as optional I preferred to go only with `class components`.

**Review by Fondem-Jr — APPROVED** [review]
# Project Approved 🚀

Hi @Ntwali-Josue  🥇,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ntwali-Josue** [comment]
@Fondem-Jr thanks for your approval man

**Pull request merged**
